---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storeapi
  template:
    metadata:
      labels:
        app: storeapi
    spec:
      containers:
      - name: storeapi-container
        image:  xorb/storeapi:1.0
        ports:                                     
        - containerPort: 8080                      
          name: http                                
---
kind: Service             
apiVersion: v1            
metadata:                 
  name: storeapi  
spec:                     
  selector:               
    app: storeapi           
  ports:                  
  - protocol: TCP         
    targetPort: http     
    port: 3000              
  type: NodePort