export const PRODUCTS = {
  GET_ALL: 'PRODUCTS_GET_ALL',
  CREATE: 'PRODUCTS_CREATE',
  CREATE_SUCCESS: 'PRODUCTS_CREATE_SUCCESS',
  UPDATE: 'PRODUCTS_UPDATE',
  DELETE: 'PRODUCTS_DELETE',
  GET_ALL_SUCCESS: 'PRODUCTS_GEL_ALL_SUCCESS'
}

export const CARTITEMS = {
  GET_ALL: 'CARTITEMS_GET_ALL',
  SET_ALL: 'CART_ITEMS_SET_ALL'
}
